In [1]:
import numpy as np

a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

a + b

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

A variavel "a" cria uma matriz  de três elementos( de acordo com o argumento inserido).

Já a variavel "b" possui um função  a mais "np.newaxis",que 
fatia cada elemento da matriz criado em outras matrizes independetes dentro de um mesmo.

A operação final "a+b", faz a soma das mastrizes criadas anterioermente e exibe
seus resultados dentro de uma unica matriz.

Grupo:

Caroline-TIA: 31847341	
Luiz-TIA: 31861806
Kaique-TIA: 31844812
Nicolle-TIA: 31810446
